#!/usr/bin/env bash
# =============================================================================
# 03-configure-ipfs-chromium.sh
#
# WHAT THIS DOES:
#   Configures the ipfs-chromium build system on top of the Chromium source
#   tree you fetched in step 02.  After this script finishes you will have
#   a fully configured build directory, ready for "cmake --build".
#
#   Specifically:
#     1. Points CMake at your Chromium checkout
#     2. Generates the build directory with Ninja
#     3. Runs the "setup_in_tree" target (patches Chromium, syncs sources)
#     4. Prints the exact command to build the browser
#
#   It does NOT start the actual build (that takes hours).
#
# HOW TO RUN:
#   chmod +x 03-configure-ipfs-chromium.sh
#   ./03-configure-ipfs-chromium.sh
#
# OPTIONS:
#   You can set these environment variables before running:
#
#     CHROMIUM_DIR    Where Chromium was checked out.
#                     Default: ~/chromium
#
#     BUILD_DIR       Where to put the ipfs-chromium build.
#                     Default: ~/ipfs-chromium-build
#
#     BUILD_TYPE      "Debug" or "Release".
#                     Default: Debug
#
#     CHROMIUM_PROFILE  The Chromium output profile name.
#                       Default: same as BUILD_TYPE
#
# AFTER THIS SCRIPT:
#   To do the actual build (this will take a LONG time):
#
#     cmake --build ~/ipfs-chromium-build --target build_browser
#
# =============================================================================
set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────────────
CHROMIUM_DIR="${CHROMIUM_DIR:-${HOME}/chromium}"
CHROMIUM_SRC="${CHROMIUM_DIR}/src"
BUILD_DIR="${BUILD_DIR:-${HOME}/ipfs-chromium-build}"
BUILD_TYPE="${BUILD_TYPE:-Debug}"
CHROMIUM_PROFILE="${CHROMIUM_PROFILE:-${BUILD_TYPE}}"

# Figure out where ipfs-chromium source lives (this repo)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IPFS_CHROMIUM_SRC="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo ""
echo "========================================"
echo "  Step 3: Configure IPFS-Chromium"
echo "========================================"
echo ""
echo "  ipfs-chromium source : ${IPFS_CHROMIUM_SRC}"
echo "  Chromium source      : ${CHROMIUM_SRC}"
echo "  Build directory      : ${BUILD_DIR}"
echo "  Build type           : ${BUILD_TYPE}"
echo "  Chromium profile     : ${CHROMIUM_PROFILE}"
echo ""

# ── Sanity checks ──────────────────────────────────────────────────────────
if [ ! -d "${CHROMIUM_SRC}/.git" ]; then
    echo "ERROR: Chromium source not found at ${CHROMIUM_SRC}"
    echo ""
    echo "  Either run 02-fetch-chromium.sh first, or set CHROMIUM_DIR:"
    echo "    CHROMIUM_DIR=/path/to/chromium ./03-configure-ipfs-chromium.sh"
    exit 1
fi

if ! command -v cmake &>/dev/null; then
    echo "ERROR: cmake not found. Run 01-system-packages.sh first."
    exit 1
fi

if ! command -v ninja &>/dev/null; then
    echo "ERROR: ninja not found. Run 01-system-packages.sh first."
    exit 1
fi

# ── 1. Create the Chromium output directory if needed ──────────────────────
CHROMIUM_OUT="${CHROMIUM_SRC}/out/${CHROMIUM_PROFILE}"
if [ ! -d "${CHROMIUM_OUT}" ]; then
    echo ">>> Creating Chromium output directory: ${CHROMIUM_OUT}"
    mkdir -p "${CHROMIUM_OUT}"

    # Generate a minimal args.gn so gn gen can succeed
    echo "  Writing initial args.gn..."
    cat > "${CHROMIUM_OUT}/args.gn" <<GNEOF
# Generated by ipfs-chromium bootstrap
enable_ipfs = true
GNEOF

    if [ "${BUILD_TYPE}" = "Release" ]; then
        cat >> "${CHROMIUM_OUT}/args.gn" <<GNEOF
is_debug = false
is_component_build = false
dcheck_always_on = false
GNEOF
    else
        cat >> "${CHROMIUM_OUT}/args.gn" <<GNEOF
is_debug = true
dcheck_always_on = true
symbol_level = 2
GNEOF
    fi

    # ccache for faster rebuilds
    if command -v ccache &>/dev/null; then
        ccache_path="$(which ccache)"
        echo "cc_wrapper = \"${ccache_path}\"" >> "${CHROMIUM_OUT}/args.gn"
        echo "  Added ccache to args.gn"
    fi

    echo ""
    echo "  args.gn written to: ${CHROMIUM_OUT}/args.gn"
    echo "  Contents:"
    sed 's/^/    /' "${CHROMIUM_OUT}/args.gn"
    echo ""
fi

# ── 2. CMake configure ─────────────────────────────────────────────────────
echo ""
echo "========================================"
echo "  Running CMake configure"
echo "========================================"
echo ""

mkdir -p "${BUILD_DIR}"

cmake \
    -G Ninja \
    -S "${IPFS_CHROMIUM_SRC}" \
    -B "${BUILD_DIR}" \
    -D CMAKE_BUILD_TYPE="${BUILD_TYPE}" \
    -D CHROMIUM_SOURCE_TREE="${CHROMIUM_SRC}" \
    -D CHROMIUM_PROFILE="${CHROMIUM_PROFILE}" \
    -D USE_DOXYGEN=FALSE

echo ""
echo "  [OK] CMake configure complete."

# ── 3. Setup in-tree ───────────────────────────────────────────────────────
echo ""
echo "========================================"
echo "  Patching Chromium (setup_in_tree)"
echo "========================================"
echo ""
echo "  This copies ipfs-chromium sources into the Chromium tree and"
echo "  applies version-specific patches."
echo ""

cmake --build "${BUILD_DIR}" --target setup_in_tree

echo ""
echo "  [OK] Chromium tree is patched and ready."

# ── 4. Done ─────────────────────────────────────────────────────────────────
echo ""
echo "========================================"
echo "  DONE!  Everything is configured."
echo "========================================"
echo ""
echo "  Your build directory: ${BUILD_DIR}"
echo "  Chromium output dir : ${CHROMIUM_OUT}"
echo ""
echo "  ====================================================="
echo "  TO BUILD THE BROWSER (this will take a long time):"
echo ""
echo "    cmake --build ${BUILD_DIR} --target build_browser"
echo ""
echo "  ====================================================="
echo ""
echo "  Other useful targets:"
echo "    in_tree_lib       Build just the IPFS client library"
echo "    in_tree_build     Build just the IPFS component"
echo "    build_browser     Build the full Chromium browser"
echo "    build_electron    Build Electron instead"
echo ""
echo "  The browser binary will appear at:"
echo "    ${CHROMIUM_OUT}/chrome"
echo ""
